---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[ubuntu]
      - recipe[postgresql::server]
      - recipe[database::postgresql]
      - recipe[flyway-cli::default]
      - recipe[flyway-cli::test]
      - recipe[flyway-cli::migrate]
    attributes:
      apt:
        compile_time_update: true
      ubuntu:
        archive_url: http://it.archive.ubuntu.com/ubuntu
      postgresql:
        version: "9.3"
        enable_pgdg_apt: true
        password:
          postgres: admin
      flyway:
        confs:
          pippo:
            jdbc_url: jdbc:postgresql://localhost:5432/pippo
            jdbc_username: pippo
            jdbc_password: pippo
          pippo2:
            use_data_bag: true
            data_bag_name: flyway
            data_bag_item: flyway-item
            jdbc_url: jdbc:postgresql://localhost:5432/pippo2
            options:
              flyway.table: alternate_schema_version
              flyway.encoding: UTF-8
