---
suites:
  - name: default
    run_list:
      - recipe[ubuntu]
      - recipe[postgresql::server]
      - recipe[database::postgresql]
      - recipe[flyway-cli::default]
      - recipe[flyway-cli::test]
      - recipe[flyway-cli::migrate]
    attributes:
      ubuntu:
        archive_url: http://it.archive.ubuntu.com/ubuntu
      postgresql:
        version: "9.4"
        enable_pgdg_apt: true
        password:
          postgres: admin
      flyway:
        confs:
          pippo:
            jdbc_url: jdbc:postgresql://localhost:5432/pippo
            jdbc_username: pippo
            jdbc_password: pippo
          pippo2:
            jdbc_url: jdbc:postgresql://localhost:5432/pippo2
            jdbc_username: pippo2
            jdbc_password: pippo2
