---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ubuntu]
      - recipe[java]
      - recipe[flyway-cli::default]
      - recipe[flyway-cli::test]
      - recipe[flyway-cli::migrate]
    attributes:
      ubuntu:
        archive_url: http://it.archive.ubuntu.com/ubuntu
      postgresql:
        password:
          postgres: admin
      flyway:
        confs:
          pippo:
            jdbc_url: jdbc:postgresql://localhost:5432/pippo
            jdbc_username: pippo
            jdbc_password: pippo
          pippo2:
            jdbc_url: jdbc:postgresql://localhost:5432/pippo2
            jdbc_username: pippo2
            jdbc_password: pippo2
