---
driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: test/integration/default/data_bags
    encrypted_data_bag_secret_key_path: test/integration/default/encrypted_data_bag_secret
    run_list:
      - recipe[ubuntu]
      - recipe[postgresql::server]
      - recipe[database::postgresql]
      - recipe[flyway_cli_tester]
      - recipe[flyway-cli]
    attributes:
      apt:
        compile_time_update: true
      ubuntu:
        archive_url: http://it.archive.ubuntu.com/ubuntu
      postgresql:
        version: "9.3"
        enable_pgdg_apt: true
        password:
          postgres: admin
      flyway:
        confs:
          pippo:
            jdbc_url: jdbc:postgresql://localhost:5432/pippo
            jdbc_username: pippo
            jdbc_password: pippo
            migrations_url: file:////tmp/migrations.tar.gz
          pippo2:
            data_bag:
              name: flyway
              item: flyway-item
            jdbc_url: jdbc:postgresql://localhost:5432/pippo2
            options:
              flyway.table: alternate_schema_version
              flyway.encoding: UTF-8
            migrations_url: file:////tmp/migrations.tar.gz
