rvm: 2.2

sudo: required
services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1404

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.16.28
install: chef exec bundle install --jobs=3 --retry=3

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - foodcritic --version
  - foodcritic . --exclude spec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml chef exec bundle exec kitchen verify ${INSTANCE}
