name             'flyway-cli'
maintainer       'ClouDesire'
maintainer_email 'dev@cloudesire.com'
license          'Apache 2.0'
description      'Installs and execute flyway cli'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
supports         'ubuntu'
depends          'apt'
depends          'java'
